name: field.blocks.gallery.name
icon: dashboard
preview: gallery
fields:
  images:
    label: field.blocks.gallery.images.label
    type: files
    query: model.images
    multiple: true
    layout: cards
    size: tiny
    empty: field.blocks.gallery.images.empty
    uploads:
      template: blocks/image
    image:
      ratio: 1/1
  caption:
    label: field.blocks.image.caption
    type: writer
    icon: text
    inline: true
  ratio:
    label: field.blocks.image.ratio
    type: select
    placeholder: Auto
    width: 1/2
    options:
      1/1: "1:1"
      16/9: "16:9"
      9/16: "9:16"
      5/4: "5:4"
      4/5: "4:5"
      4/3: "4:3"
      3/4: "3:4"
      3/2: "3:2"
      2/3: "2:3"
  crop:
    label: field.blocks.image.crop
    type: toggle
    width: 1/2
  portrait:
    label: field.blocks.image.portrait
    type: toggle
    width: 1/2
