title: Site

columns:
  artists:
    width: 1/2
    sections:
      artists: sections/artists

  essays:
    width: 1/2
    sections:
      essays: sections/essays

  menus:
    width: 1/2
    sections:
      menus:
        type: fields
        fields:
          introduction:
            label: Introduction
            type: textarea
          recordings:
            label: Recordings
            type: textarea
          contact:
            label: Contact
            type: textarea
          accessibility:
            label: Accessibility
            type: textarea

  accessibilitystatement:
    width: 1/2
    sections:
      accessibilitystatement:
        type: fields
        fields:
          accessibilitystatement:
            label: Accessibility Statement
            type: textarea