title: Site

columns:
  artists:
    width: 1/2
    sections:
      artists: sections/artists

  essays:
    width: 1/2
    sections:
      essays: sections/essays

  introduction:
    width: 1/2
    sections:
      introduction:
        type: fields
        fields:
          introduction:
            label: Introduction
            type:  textarea
  recordings:
    width: 1/2
    sections:
      recordings:
        type: fields
        fields:
          recordings:
            label: Recordings
            type:  textarea
  contact:
    width: 1/2
    sections:
      contact:
        type: fields
        fields:
          contact:
            label: Contact
            type:  textarea

  accessibility:
    width: 1/2
    sections:
      accessibility:
        type: fields
        fields:
          accessibility:
            label: Accessibility Statement
            type:  textarea